import path from 'path';
import fs from 'fs/promises';
import { app } from 'electron';
import { google, drive_v3 } from 'googleapis';
import type { OAuth2Client } from 'google-auth-library';
import { DatabaseManager } from '../db/database';

export class ThumbnailService {
  private db: DatabaseManager;
  private thumbnailDir: string;
  private drive: drive_v3.Drive | null = null;
  private authClient: OAuth2Client | null;

  constructor(db: DatabaseManager, authClient?: OAuth2Client) {
    this.db = db;
    const userDataPath = app?.getPath('userData') || __dirname;
    this.thumbnailDir = path.join(userDataPath, 'thumbnails');
    this.authClient = authClient || null;

    if (this.authClient) {
      this.drive = google.drive({ version: 'v3', auth: this.authClient });
    }
  }

  async ensureDirectoryExists(): Promise<void> {
    try {
      await fs.mkdir(this.thumbnailDir, { recursive: true });
    } catch (error) {
      // Directory might already exist
    }
  }

  getThumbnailPath(fileId: string): string {
    return path.join(this.thumbnailDir, `${fileId}.png`);
  }

  async hasThumbnail(fileId: string): Promise<boolean> {
    try {
      await fs.access(this.getThumbnailPath(fileId));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get thumbnail URL from Google Drive
   * Note: Google Drive only generates thumbnails for PDFs when they're viewed in Drive's UI
   * Most community drive PDFs won't have thumbnails available
   */
  async getGoogleThumbnailUrl(fileId: string, size: number = 400): Promise<string | null> {
    // If we have API access, check if the file has a thumbnail
    if (this.drive) {
      try {
        const response = await this.drive.files.get({
          fileId: fileId,
          fields: 'thumbnailLink,hasThumbnail',
          supportsAllDrives: true
        });
        
        // Only return URL if the file actually has a thumbnail
        if (response.data.hasThumbnail && response.data.thumbnailLink) {
          // The API returns a URL like: https://lh3.googleusercontent.com/...
          // Modify size parameter
          let url = response.data.thumbnailLink;
          // Replace existing size or add one
          if (url.includes('=s')) {
            url = url.replace(/=s\d+/, `=s${size}`);
          } else if (url.includes('=')) {
            url = url.replace(/=$/, `=s${size}`);
          } else {
            url = `${url}=s${size}`;
          }
          return url;
        }
        
        // File exists but has no thumbnail generated by Google
        // This is normal for PDFs that haven't been viewed in Drive's web UI
        return null;
      } catch (error) {
        // API error - log and fall through to public URL
        const errorMsg = (error as Error).message;
        // Only log unexpected errors (not rate limits or common issues)
        if (!errorMsg.includes('Rate Limit') && !errorMsg.includes('quota')) {
          console.warn(`Thumbnail API error for ${fileId}:`, errorMsg);
        }
      }
    }
    
    // No API or API failed - use public URL as fallback
    // Note: This often returns a generic PDF icon or fails for non-public files
    return `https://drive.google.com/thumbnail?id=${fileId}&sz=w${size}`;
  }

  /**
   * Download and cache a thumbnail from Google Drive
   * Note: Google Drive thumbnails may not be available for all files
   */
  async cacheThumbnail(fileId: string): Promise<string | null> {
    await this.ensureDirectoryExists();
    
    const thumbnailPath = this.getThumbnailPath(fileId);
    
    // Check if already cached
    if (await this.hasThumbnail(fileId)) {
      return thumbnailPath;
    }

    try {
      const url = await this.getGoogleThumbnailUrl(fileId);
      
      if (!url) {
        console.warn(`No thumbnail URL available for ${fileId}`);
        return null;
      }
      
      // Create abort controller for timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout
      
      const response = await fetch(url, {
        signal: controller.signal
      });
      
      clearTimeout(timeoutId);
      
      if (!response.ok) {
        // Don't log 404s as errors - some files just don't have thumbnails
        if (response.status !== 404) {
          console.warn(`Failed to fetch thumbnail for ${fileId}: ${response.status}`);
        }
        return null;
      }

      // Verify it's actually an image
      const contentType = response.headers.get('content-type');
      if (!contentType || !contentType.startsWith('image/')) {
        console.warn(`Thumbnail for ${fileId} is not an image: ${contentType}`);
        return null;
      }

      const buffer = await response.arrayBuffer();
      
      // Verify we got actual image data
      if (buffer.byteLength === 0) {
        console.warn(`Empty thumbnail data for ${fileId}`);
        return null;
      }
      
      await fs.writeFile(thumbnailPath, Buffer.from(buffer));
      
      // Update database
      this.db.updateThumbnailPath(fileId, thumbnailPath);
      
      return thumbnailPath;
    } catch (error) {
      // Don't log timeout errors as errors - they're expected for some files
      if ((error as Error).name !== 'AbortError') {
        console.error(`Error caching thumbnail for ${fileId}:`, error);
      }
      return null;
    }
  }

  /**
   * Get thumbnail - returns Google URL directly (simpler and more reliable)
   * Caching is done in background and served on subsequent requests
   */
  async getThumbnail(fileId: string): Promise<{ type: 'local' | 'url'; path: string }> {
    const localPath = this.getThumbnailPath(fileId);
    
    // Check if we have a local cached version
    if (await this.hasThumbnail(fileId)) {
      try {
        // Read the file and convert to data URL
        const imageBuffer = await fs.readFile(localPath);
        const base64 = imageBuffer.toString('base64');
        // Detect mime type from file content
        const mimeType = this.detectMimeType(imageBuffer) || 'image/png';
        const dataUrl = `data:${mimeType};base64,${base64}`;
        return { type: 'local', path: dataUrl };
      } catch (error) {
        console.error(`Failed to read thumbnail file ${localPath}:`, error);
        // Fall through to Google URL
      }
    }

    // Get thumbnail URL from Google Drive
    const googleUrl = await this.getGoogleThumbnailUrl(fileId);
    
    if (googleUrl) {
      // Try to cache in background for future use (but don't wait for it)
      this.cacheThumbnail(fileId).catch(() => {
        // Silently ignore cache failures
      });
      return { type: 'url', path: googleUrl };
    }
    
    // No thumbnail available - Google Drive doesn't generate thumbnails for most PDFs
    // unless they've been viewed in Drive's web interface
    return { type: 'url', path: '' };
  }

  /**
   * Detect MIME type from image buffer
   */
  private detectMimeType(buffer: Buffer): string | null {
    if (buffer[0] === 0x89 && buffer[1] === 0x50 && buffer[2] === 0x4E && buffer[3] === 0x47) {
      return 'image/png';
    }
    if (buffer[0] === 0xFF && buffer[1] === 0xD8 && buffer[2] === 0xFF) {
      return 'image/jpeg';
    }
    if (buffer[0] === 0x47 && buffer[1] === 0x49 && buffer[2] === 0x46) {
      return 'image/gif';
    }
    if (buffer[0] === 0x52 && buffer[1] === 0x49 && buffer[2] === 0x46 && buffer[3] === 0x46) {
      return 'image/webp';
    }
    return null;
  }

  /**
   * Clear thumbnail cache
   */
  async clearCache(): Promise<void> {
    try {
      const files = await fs.readdir(this.thumbnailDir);
      await Promise.all(
        files.map(file => fs.unlink(path.join(this.thumbnailDir, file)))
      );
    } catch (error) {
      console.error('Error clearing thumbnail cache:', error);
    }
  }

  /**
   * Get cache size in bytes
   */
  async getCacheSize(): Promise<number> {
    try {
      const files = await fs.readdir(this.thumbnailDir);
      let totalSize = 0;
      
      for (const file of files) {
        const stat = await fs.stat(path.join(this.thumbnailDir, file));
        totalSize += stat.size;
      }
      
      return totalSize;
    } catch {
      return 0;
    }
  }
}
